import { useState } from 'react'
import * as Accordion from '@radix-ui/react-accordion'
import { ArrowRight, Atom, CalendarDays, Check, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, CircleDollarSign, Facebook, FlaskConical, Instagram, Leaf, Linkedin, Menu, Pill, Rabbit, Send, Sparkles, Star, Syringe, TreePine, Truck, UserRound, Wheat, X, Youtube } from 'lucide-react'

const IMAGES = { clinical: '/images/clinical-product.png', supplements: '/images/supplements.png', lifestyle: '/images/lifestyle.png', editorial: '/images/editorial.png' }
const products = [
  { title: 'Compounded Semaglutide', price: '$196', image: IMAGES.clinical },
  { title: 'Daily Metabolic Support', price: '$89', image: IMAGES.supplements },
  { title: 'Whole Body Reset', price: '$149', image: IMAGES.editorial },
]
const carousel = [
  { eyebrow: 'Healthy aging', title: 'Live well, for longer.', price: '$79', image: IMAGES.lifestyle },
  { eyebrow: 'Daily wellness', title: 'Feel like yourself again.', price: '$49', image: IMAGES.editorial },
  { eyebrow: 'Metabolic care', title: 'Support that fits your life.', price: '$89', image: IMAGES.supplements },
]
const faqs = [
  ['What is included in the GLP-1 program?', 'Your plan includes an online medical intake, clinician review, medication when prescribed, ongoing check-ins, and unlimited support from your care team.'],
  ['Do I need insurance?', 'No. Our programs are designed to be accessible without insurance, and pricing is transparent from the start. HSA and FSA cards may be accepted.'],
  ['Which medications do you offer?', 'Licensed clinicians may prescribe compounded semaglutide or other treatments based on medical eligibility, personal goals, and availability.'],
  ['Will my price change when my dose changes?', 'No. Your monthly medication price stays the same at every prescribed dose, so there are no surprises as your plan evolves.'],
  ['What does my monthly plan include?', 'Each plan includes medication when prescribed, supplies, shipping, progress tracking, and ongoing access to your clinical care team.'],
]
const guides = [
  ['Weight loss', 'How GLP-1 medications support sustainable weight loss', IMAGES.clinical],
  ['Wellness', 'Five small habits that make healthy routines stick', IMAGES.lifestyle],
  ['Nutrition', 'A practical guide to eating well on a busy schedule', IMAGES.editorial],
  ['Healthy aging', 'Building strength, energy, and confidence at every age', IMAGES.supplements],
]

function GradientButton({ children, className = '', href = '#products' }: { children: React.ReactNode; className?: string; href?: string }) { return <a href={href} className={`gradient-frame group inline-flex rounded-full p-[2px] ${className}`}><span className="flex h-full w-full items-center justify-center gap-2 rounded-full bg-background px-6 py-3 text-sm font-semibold text-foreground transition-colors group-hover:bg-white">{children}</span></a> }
function DarkButton({ children, className = '', href = '#products' }: { children: React.ReactNode; className?: string; href?: string }) { return <a href={href} className={`inline-flex items-center justify-center gap-2 rounded-full bg-zinc-900 px-6 py-3 text-sm font-semibold text-white transition hover:bg-zinc-700 ${className}`}>{children}</a> }
function Heading({ eyebrow, children }: { eyebrow: string; children: React.ReactNode }) { return <div className="mx-auto max-w-4xl text-center"><p className="eyebrow">{eyebrow}</p><h2 className="mt-5 text-4xl font-semibold leading-[1.02] tracking-[-.045em] sm:text-5xl lg:text-6xl">{children}</h2></div> }

function App() {
  const [menu, setMenu] = useState(false)
  const [slide, setSlide] = useState(0)
  const next = (n: number) => setSlide((s) => (s + n + carousel.length) % carousel.length)
  return <div className="min-h-screen overflow-hidden bg-background text-foreground">
    <header className="sticky top-0 z-50 border-b border-black/5 bg-[#faf9f7]/90 backdrop-blur-xl"><nav className="mx-auto flex h-[76px] max-w-[1440px] items-center justify-between px-5 sm:px-8 lg:px-12"><a className="text-xl font-semibold tracking-tight" href="#">Logo<span className="text-[#df6da8]">.</span></a><div className="hidden items-center gap-7 lg:flex">{['Weight Loss','Strength','Anti-Aging','Hair Growth','Mood','More'].map(x => <a className="text-sm font-medium hover:opacity-50" href="#products" key={x}>{x}</a>)}</div><div className="flex items-center gap-3"><DarkButton className="hidden sm:inline-flex">Get started <ArrowRight size={16}/></DarkButton><GradientButton className="hidden sm:inline-flex"><UserRound size={16}/> Login</GradientButton><button aria-label="Toggle menu" className="grid size-11 place-items-center rounded-full border border-black/10 lg:hidden" onClick={() => setMenu(!menu)}>{menu ? <X size={20}/> : <Menu size={20}/>}</button></div></nav>{menu && <div className="border-t border-black/5 bg-background px-5 py-5 lg:hidden"><div className="grid gap-1">{['Weight Loss','Strength','Anti-Aging','Hair Growth','Mood','More'].map(x => <a className="rounded-xl px-3 py-3 font-medium hover:bg-black/5" href="#products" key={x}>{x}</a>)}</div></div>}</header>
    <main>
      <section className="mx-auto grid min-h-[780px] max-w-[1440px] lg:grid-cols-[.92fr_1.08fr]"><div className="flex flex-col justify-center px-5 py-20 sm:px-8 lg:px-12"><div className="mb-8 flex w-fit items-center gap-2 rounded-full bg-white py-2 pl-2 pr-4 text-xs font-semibold shadow-soft sm:text-sm"><span className="grid size-7 place-items-center rounded-full bg-[#5e7558] text-white"><Star size={14} fill="currentColor"/></span><span>4.5 Average Rating</span><span className="text-black/35">•</span><span className="text-black/55">453 Reviews</span></div><p className="mb-5 text-xs font-bold uppercase tracking-[.22em] text-black/45">Doctor-led weight care</p><h1 className="max-w-2xl text-[2.8rem] font-semibold leading-[.98] tracking-[-.055em] sm:text-6xl lg:text-[4.65rem]">Compounded Semaglutide for Weight Loss</h1><div className="my-10 grid gap-5">{[[Syringe,'Clinician-prescribed, personalized to you'],[CircleDollarSign,'One transparent price at every dose'],[Truck,'Free, discreet delivery to your door']].map(([Icon,t]) => <div className="flex items-center gap-4 text-[15px] font-medium" key={t as string}><span className="grid size-10 place-items-center rounded-full bg-[#f0ebe7]"><Icon size={19}/></span>{t as string}</div>)}</div><div className="border-t border-black/10 pt-7"><div className="flex flex-wrap items-center gap-4"><div><span className="text-3xl font-semibold tracking-tight">$296</span><span>/mo</span><p className="text-xs text-black/50">*No matter the dose</p></div><DarkButton className="ml-auto">Get started <ArrowRight size={16}/></DarkButton></div><a href="#faq" className="mt-8 flex max-w-md items-center gap-4 rounded-2xl bg-white p-3 pr-5 shadow-soft"><img className="size-16 rounded-xl object-cover" src={IMAGES.lifestyle} alt="Healthy woman"/><span className="text-sm"><b className="block">Is This Right for You?</b><span className="text-black/50">Take our 2-minute assessment</span></span><ArrowRight className="ml-auto" size={18}/></a></div></div><div className="relative hidden h-[780px] gap-4 overflow-hidden bg-[#ece6e0] p-4 lg:grid lg:grid-cols-2"><div className="absolute inset-x-0 top-0 z-10 h-32 bg-gradient-to-b from-[#ece6e0] to-transparent"/><div className="absolute inset-x-0 bottom-0 z-10 h-32 bg-gradient-to-t from-[#ece6e0] to-transparent"/><Marquee images={[IMAGES.clinical,IMAGES.lifestyle,IMAGES.supplements,IMAGES.editorial]}/><Marquee images={[IMAGES.editorial,IMAGES.supplements,IMAGES.lifestyle,IMAGES.clinical]} reverse/></div></section>
      <section id="products" className="bg-white px-5 py-24 sm:px-8 lg:px-12 lg:py-32"><div className="mx-auto max-w-[1320px]"><Heading eyebrow="Our meds">Medication made affordable<br className="hidden sm:block"/> without the insurance</Heading><div className="mt-14 grid gap-10 md:grid-cols-2 lg:grid-cols-3">{products.map(p => <article className="group" key={p.title}><div className="aspect-square overflow-hidden rounded-[2rem] shadow-soft transition group-hover:-translate-y-1 group-hover:shadow-xl"><img className="h-full w-full object-cover transition duration-700 group-hover:scale-105" src={p.image} alt={p.title}/></div><h3 className="mt-6 text-2xl font-semibold tracking-tight">{p.title}</h3><p className="mt-1 text-lg font-semibold">{p.price} <span className="text-sm font-normal text-black/50">per month</span></p><GradientButton className="mt-5 w-full">Get started <ArrowRight size={16}/></GradientButton></article>)}</div></div></section>
      <section className="bg-[#f7f6f4] px-5 py-24 sm:px-8 lg:px-12 lg:py-32"><div className="mx-auto grid max-w-[1320px] items-center gap-14 lg:grid-cols-2 lg:gap-24"><div><p className="eyebrow">Weight loss, made personal</p><h2 className="mt-5 text-4xl font-semibold leading-[1.02] tracking-[-.045em] sm:text-5xl lg:text-6xl">Lose weight with a plan made just for you.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-black/55">Expert care, ongoing support, and treatment that adapts as you do. No waiting rooms, no judgment.</p><div className="my-9 grid gap-5">{[[CalendarDays,'Meet your clinician online'],[Pill,'Receive treatment at your door'],[CheckCircle2,'Get support at every milestone']].map(([Icon,t]) => <div className="flex items-center gap-4 font-medium" key={t as string}><span className="grid size-11 place-items-center rounded-full bg-white shadow-sm"><Icon size={20}/></span>{t as string}</div>)}</div><div className="flex flex-wrap gap-3"><DarkButton>Get started <ArrowRight size={16}/></DarkButton><GradientButton>See if you’re eligible</GradientButton></div></div><div className="relative"><img className="aspect-[4/5] w-full rounded-[2rem] object-cover shadow-soft" src={IMAGES.lifestyle} alt="Woman holding water"/><div className="absolute bottom-5 left-5 rounded-2xl bg-white/90 p-4 shadow-soft"><span className="flex items-center gap-3 text-sm font-medium"><span className="grid size-10 place-items-center rounded-full bg-[#e5f0df]"><Check size={18}/></span>Care that keeps up</span></div></div></div></section>
      <section className="bg-[#ededeb] px-5 py-24 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1320px] gap-6 lg:grid-cols-[.82fr_1.18fr]"><Promo item={{eyebrow:'Weight care',title:'Your goals. Your pace. Your plan.',price:'$196',image:IMAGES.clinical}}/><div className="relative overflow-hidden rounded-[2rem]"><div className="flex transition-transform duration-700" style={{transform:`translateX(-${slide*100}%)`}}>{carousel.map(c => <div className="min-w-full" key={c.title}><Promo item={c}/></div>)}</div><div className="absolute right-5 top-5 flex gap-2"><button onClick={() => next(-1)} className="grid size-11 place-items-center rounded-full bg-white/85"><ChevronLeft size={19}/></button><button onClick={() => next(1)} className="grid size-11 place-items-center rounded-full bg-white/85"><ChevronRight size={19}/></button></div></div></div></section>
      <section className="bg-[#faf9f7] px-5 py-24 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-[1320px]"><Heading eyebrow="Our standards">Discover the harmony of science and nature.</Heading><div className="mt-8 flex justify-center gap-3"><DarkButton>Our approach</DarkButton><GradientButton>Explore treatments</GradientButton></div><div className="mt-14 grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-6">{[[Rabbit,'Cruelty\nfree'],[TreePine,'Planet\nthoughtful'],[Leaf,'Carefully\nsourced'],[FlaskConical,'Clinically\nreviewed'],[Atom,'Science\nbacked'],[Wheat,'Made without\nfillers']].map(([Icon,t]) => <div className="flex min-h-56 flex-col items-center justify-center rounded-2xl bg-white p-6 text-center shadow-soft" key={t as string}><Icon className="mb-6 size-16 lg:size-20" strokeWidth={1.2}/><p className="whitespace-pre-line font-semibold leading-5">{t as string}</p></div>)}</div></div></section>
      <section id="faq" className="bg-[#faf9f7] px-5 py-24 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-4xl"><Heading eyebrow="Questions, answered">A little clarity goes a long way.</Heading><Accordion.Root type="single" collapsible className="mt-14 space-y-4">{faqs.map(([q,a],i) => <Accordion.Item key={q} value={`i${i}`} className="overflow-hidden rounded-3xl bg-white px-6 shadow-soft sm:px-12"><Accordion.Header><Accordion.Trigger className="accordion-trigger flex w-full items-center py-7 text-left text-xl font-semibold sm:text-2xl">{q}<ChevronDown className="ml-auto"/></Accordion.Trigger></Accordion.Header><Accordion.Content className="accordion-content overflow-hidden"><p className="pb-8 text-base leading-7 text-black/55 sm:text-lg">{a}</p></Accordion.Content></Accordion.Item>)}</Accordion.Root></div></section>
      <section className="bg-[#faf9f7] px-5 py-24 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-[1320px]"><Heading eyebrow="The health guide">Your guide to health and wellness starts here.</Heading><div className="mt-8 flex justify-center gap-3"><DarkButton>See all articles</DarkButton><GradientButton>Join our newsletter</GradientButton></div><div className="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{guides.map(([cat,title,image]) => <article className="group overflow-hidden rounded-3xl bg-white shadow-soft" key={title as string}><div className="h-52 overflow-hidden"><img className="h-full w-full object-cover transition duration-700 group-hover:scale-105" src={image as string} alt=""/></div><div className="flex min-h-52 flex-col p-6"><p className="text-lg font-semibold leading-6">{title as string}</p><a href="#" className="mt-auto flex w-fit items-center gap-2 rounded-full border-2 border-zinc-900/[.13] px-4 py-2 text-xs font-semibold">{cat as string}<ChevronRight size={14}/></a></div></article>)}</div></div></section>
    </main><Footer/></div>
}
function Marquee({images,reverse=false}:{images:string[];reverse?:boolean}) { return <div className="overflow-hidden"><div className={`grid gap-4 ${reverse?'animate-marquee-reverse':'animate-marquee'}`}>{[...images,...images].map((s,i)=><img className="aspect-[4/5] w-full rounded-3xl object-cover" src={s} alt="Wellness product" key={`${s}${i}`}/>)}</div></div> }
function Promo({item}:{item:{eyebrow:string;title:string;price:string;image:string}}) { return <article className="group relative h-[34rem] overflow-hidden rounded-[2rem] sm:h-[42rem] lg:h-[48rem]"><img className="absolute inset-0 h-full w-full object-cover transition duration-700 group-hover:scale-105" src={item.image} alt={item.title}/><div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/5"/><div className="absolute inset-x-0 bottom-0 p-7 text-white sm:p-10"><p className="text-xs font-bold uppercase tracking-[.2em]">{item.eyebrow}</p><p className="mt-2 text-sm text-white/75">Plans from</p><p className="text-3xl font-semibold">{item.price}<span className="text-sm font-normal">/mo</span></p><h3 className="my-5 text-3xl font-semibold leading-tight sm:text-4xl">{item.title}</h3><GradientButton><span className="text-zinc-900">Get started</span><ArrowRight className="text-zinc-900" size={16}/></GradientButton></div></article> }
function Footer(){return <footer className="bg-zinc-900 px-5 py-16 text-white sm:px-8 lg:px-12 lg:py-20"><div className="mx-auto max-w-[1320px]"><div className="grid gap-14 lg:grid-cols-2"><div><p className="text-2xl font-semibold">Logo<span className="text-[#ef8ab8]">.</span></p><h3 className="mt-8 max-w-md text-3xl font-medium leading-tight">Better health notes, straight to your inbox.</h3><form className="mt-6 flex max-w-md rounded-full bg-white p-1.5"><input className="min-w-0 flex-1 bg-transparent px-4 text-sm text-black outline-none" placeholder="Email address"/><button className="grid size-11 place-items-center rounded-full bg-zinc-900"><Send size={17}/></button></form></div><div className="grid grid-cols-3 gap-6">{[['Popular','Weight Loss','Anti-Aging','Hair Growth','Mood Care'],['Company','About','Careers','Health Guide','Reviews'],['Legal','Privacy','Terms','Accessibility','HIPAA']].map(([t,...xs])=><div key={t}><p className="mb-5 text-sm font-semibold">{t}</p><div className="grid gap-3">{xs.map(x=><a className="text-sm text-white/50 hover:text-white" href="#" key={x}>{x}</a>)}</div></div>)}</div></div><div className="my-10 border-t border-white/10"/><div className="flex flex-wrap items-center justify-between gap-8"><div className="flex gap-2">{[Facebook,Instagram,X,Sparkles,Linkedin,Youtube].map((I,i)=><a href="#" className="grid size-10 place-items-center rounded-full border border-white/15 text-white/65" key={i}><I size={17}/></a>)}</div><div className="flex gap-3"><span className="rounded-xl border border-white/15 px-4 py-2 text-xs">✓ LegitScript Certified</span><span className="rounded-xl border border-white/15 px-4 py-2 text-xs">US Compounding Pharmacy</span></div></div><p className="mt-10 text-[11px] leading-5 text-white/35">Compounded medications are prepared by state-licensed compounding pharmacies and are not reviewed by the FDA for safety, effectiveness, or quality. © 2026 Logo Health, Inc.</p></div></footer>}
export default App
