import { useCallback, useEffect, useState } from 'react'
import { Loader2, Mail, RefreshCw, UserMinus, UserPlus } from 'lucide-react'
import { adminApi, AdminApiError } from '../../lib/admin-api'
import { formatAdminDate } from './order-utils'

interface Subscriber { id: string; email: string; status: string; consentAt: number; unsubscribedAt: number | null; createdAt: number; updatedAt: number }
const STATUS_LABELS: Record<string, string> = { pending: 'Chờ xác nhận', active: 'Đang nhận tin', unsubscribed: 'Đã hủy' }

export default function AdminNewsletter() {
  const [subscribers, setSubscribers] = useState<Subscriber[]>([])
  const [status, setStatus] = useState('')
  const [isLoading, setIsLoading] = useState(true)
  const [savingId, setSavingId] = useState('')
  const [error, setError] = useState('')
  const load = useCallback(async () => { setIsLoading(true); setError(''); try { const query = status ? `?status=${status}&limit=50` : '?limit=50'; const response = await adminApi<{ data: { items: Subscriber[] } }>(`/api/v1/admin/newsletter${query}`); setSubscribers(response.data.items) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Không thể tải subscribers.') } finally { setIsLoading(false) } }, [status])
  useEffect(() => { void load() }, [load])
  const updateStatus = async (subscriber: Subscriber, next: string) => { setSavingId(subscriber.id); try { await adminApi(`/api/v1/admin/newsletter/${subscriber.id}`, { method: 'PATCH', body: JSON.stringify({ status: next, updatedAt: subscriber.updatedAt }) }); await load() } catch (cause) { setError(cause instanceof AdminApiError ? cause.message : 'Không thể cập nhật subscriber.') } finally { setSavingId('') } }
  return <div className="admin-page"><div className="admin-page-heading"><div><p className="admin-eyebrow">Operations / Newsletter</p><h1 className="admin-page-title">Newsletter</h1><p className="admin-page-description">Theo dõi consent và trạng thái nhận tin của người đăng ký.</p></div><button type="button" className="admin-secondary-button" onClick={() => void load()} disabled={isLoading}><RefreshCw size={16} className={isLoading ? 'animate-spin' : ''} aria-hidden="true" /> Làm mới</button></div><div className="admin-toolbar"><label className="admin-field admin-toolbar-field"><span className="sr-only">Trạng thái</span><select value={status} onChange={event => setStatus(event.target.value)}><option value="">Tất cả</option><option value="active">Đang nhận tin</option><option value="pending">Chờ xác nhận</option><option value="unsubscribed">Đã hủy</option></select></label></div>{error && <div className="admin-alert admin-alert-error" role="alert"><span>{error}</span><button type="button" onClick={() => void load()}>Thử lại</button></div>}<section className="admin-operation-list" aria-live="polite">{isLoading ? <div className="admin-media-empty"><Loader2 size={22} className="animate-spin" aria-hidden="true" /><span>Đang tải subscribers...</span></div> : subscribers.map(subscriber => <article className="admin-operation-card admin-subscriber-card" key={subscriber.id}><div className="admin-operation-header"><div className="admin-subscriber-email"><Mail size={17} aria-hidden="true" /><h2>{subscriber.email}</h2></div><span className={`admin-status-badge ${subscriber.status === 'active' ? 'admin-tone-success' : subscriber.status === 'unsubscribed' ? 'admin-tone-danger' : 'admin-tone-warning'}`}>{STATUS_LABELS[subscriber.status] || subscriber.status}</span></div><div className="admin-subscriber-meta"><span>Consent: {formatAdminDate(subscriber.consentAt, true)}</span><span>Đăng ký: {formatAdminDate(subscriber.createdAt, true)}</span></div><div className="admin-operation-footer"><span>{subscriber.unsubscribedAt ? `Hủy lúc ${formatAdminDate(subscriber.unsubscribedAt, true)}` : 'Chưa hủy'}</span><div className="admin-operation-controls"><button type="button" className="admin-secondary-button" disabled={savingId === subscriber.id || subscriber.status === 'active'} onClick={() => void updateStatus(subscriber, 'active')}><UserPlus size={14} aria-hidden="true" /> Kích hoạt</button><button type="button" className="admin-danger-button" disabled={savingId === subscriber.id || subscriber.status === 'unsubscribed'} onClick={() => void updateStatus(subscriber, 'unsubscribed')}><UserMinus size={14} aria-hidden="true" /> Hủy nhận tin</button></div></div></article>)}{!isLoading && subscribers.length === 0 && <div className="admin-empty-state"><Mail size={24} aria-hidden="true" /><strong>Chưa có subscriber</strong><p>Danh sách sẽ xuất hiện khi khách đăng ký nhận tin.</p></div>}</section></div>
}
